"""Phase 7 publishing layer: article approvals (a decision on one exact version and quality
report; one live decision per article), publications (one per article version and CMS site,
with a unique idempotency key and the CMS post identity) and their attempts. Phase 7
publishes only approved, ready versions, WordPress drafts by default; no scheduling. No
existing row changes: the downgrade drops only these tables.

Revision ID: 0006
Revises: 0005
Create Date: 2026-09-14 23:47:35.905759
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0006"
down_revision: str | None = "0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "article_approvals",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("article_id", sa.BigInteger(), nullable=False),
        sa.Column("version_id", sa.BigInteger(), nullable=False),
        sa.Column("quality_report_id", sa.BigInteger(), nullable=False),
        sa.Column("decision", sa.String(length=16), nullable=False),
        sa.Column("method", sa.String(length=16), nullable=False),
        sa.Column("channel", sa.String(length=16), nullable=False),
        sa.Column("approver", sa.Text(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("invalidated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("invalidated_reason", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "channel IN ('api', 'cli', 'policy')", name=op.f("ck_article_approvals_channel")
        ),
        sa.CheckConstraint(
            "decision IN ('approved', 'rejected')", name=op.f("ck_article_approvals_decision")
        ),
        sa.CheckConstraint(
            "method IN ('manual', 'auto')", name=op.f("ck_article_approvals_method")
        ),
        sa.ForeignKeyConstraint(
            ["article_id"],
            ["articles.id"],
            name=op.f("fk_article_approvals_article_id_articles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["quality_report_id"],
            ["article_quality_reports.id"],
            name=op.f("fk_article_approvals_quality_report_id_article_quality_reports"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["article_versions.id"],
            name=op.f("fk_article_approvals_version_id_article_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_article_approvals")),
    )
    op.create_index(
        "ix_article_approvals_article_id_created_at",
        "article_approvals",
        ["article_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_article_approvals_quality_report_id"),
        "article_approvals",
        ["quality_report_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_article_approvals_version_id"), "article_approvals", ["version_id"], unique=False
    )
    op.create_index(
        "uq_article_approvals_live_article",
        "article_approvals",
        ["article_id"],
        unique=True,
        postgresql_where=sa.text("invalidated_at IS NULL"),
    )
    op.create_table(
        "publications",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("article_id", sa.BigInteger(), nullable=False),
        sa.Column("version_id", sa.BigInteger(), nullable=False),
        sa.Column("approval_id", sa.BigInteger(), nullable=False),
        sa.Column("cms", sa.String(length=32), nullable=False),
        sa.Column("site", sa.Text(), nullable=False),
        sa.Column("marker", sa.String(length=32), nullable=False),
        sa.Column("idempotency_key", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("target_status", sa.String(length=16), nullable=False),
        sa.Column("external_id", sa.Text(), nullable=True),
        sa.Column("external_status", sa.String(length=16), nullable=True),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("edit_url", sa.Text(), nullable=True),
        sa.Column("attempt_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column(
            "details",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("preflight", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("run_id", sa.BigInteger(), nullable=True),
        sa.Column("superseded_by_id", sa.BigInteger(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('queued', 'preflight', 'blocked', 'submitting', 'draft_created', 'published', 'failed', 'cancelled')",
            name=op.f("ck_publications_status"),
        ),
        sa.CheckConstraint(
            "target_status IN ('draft', 'pending', 'publish')",
            name=op.f("ck_publications_target_status"),
        ),
        sa.ForeignKeyConstraint(
            ["approval_id"],
            ["article_approvals.id"],
            name=op.f("fk_publications_approval_id_article_approvals"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["article_id"],
            ["articles.id"],
            name=op.f("fk_publications_article_id_articles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_publications_run_id_runs"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["superseded_by_id"],
            ["publications.id"],
            name=op.f("fk_publications_superseded_by_id_publications"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["article_versions.id"],
            name=op.f("fk_publications_version_id_article_versions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_publications")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_publications_idempotency_key")),
    )
    op.create_index(
        op.f("ix_publications_approval_id"), "publications", ["approval_id"], unique=False
    )
    op.create_index(
        "ix_publications_article_id_created_at",
        "publications",
        ["article_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_publications_version_id"), "publications", ["version_id"], unique=False
    )
    op.create_table(
        "publication_attempts",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("publication_id", sa.BigInteger(), nullable=False),
        sa.Column("run_id", sa.BigInteger(), nullable=True),
        sa.Column("action", sa.String(length=16), nullable=False),
        sa.Column("outcome", sa.String(length=16), nullable=False),
        sa.Column("http_status", sa.Integer(), nullable=True),
        sa.Column("external_id", sa.Text(), nullable=True),
        sa.Column("payload_hash", sa.String(length=64), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "action IN ('create', 'update', 'publish', 'reconcile', 'terms')",
            name=op.f("ck_publication_attempts_action"),
        ),
        sa.CheckConstraint(
            "outcome IN ('succeeded', 'failed', 'unknown')",
            name=op.f("ck_publication_attempts_outcome"),
        ),
        sa.ForeignKeyConstraint(
            ["publication_id"],
            ["publications.id"],
            name=op.f("fk_publication_attempts_publication_id_publications"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
            name=op.f("fk_publication_attempts_run_id_runs"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_publication_attempts")),
    )
    op.create_index(
        op.f("ix_publication_attempts_publication_id"),
        "publication_attempts",
        ["publication_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_publication_attempts_publication_id"), table_name="publication_attempts")
    op.drop_table("publication_attempts")
    op.drop_index(op.f("ix_publications_version_id"), table_name="publications")
    op.drop_index("ix_publications_article_id_created_at", table_name="publications")
    op.drop_index(op.f("ix_publications_approval_id"), table_name="publications")
    op.drop_table("publications")
    op.drop_index(
        "uq_article_approvals_live_article",
        table_name="article_approvals",
        postgresql_where=sa.text("invalidated_at IS NULL"),
    )
    op.drop_index(op.f("ix_article_approvals_version_id"), table_name="article_approvals")
    op.drop_index(op.f("ix_article_approvals_quality_report_id"), table_name="article_approvals")
    op.drop_index("ix_article_approvals_article_id_created_at", table_name="article_approvals")
    op.drop_table("article_approvals")
    # ### end Alembic commands ###
