"""Phase 3 analysis layer: topics + aliases, content analyses, change summaries, competitor
profiles, landscape reports; and the LLM call ledger (ops).

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-13 22:57:10.051668
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "topics",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("slug", sa.String(length=200), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("parent_id", sa.BigInteger(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("merged_into_id", sa.BigInteger(), nullable=True),
        sa.Column("origin", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("origin IN ('seed', 'llm', 'manual')", name=op.f("ck_topics_origin")),
        sa.CheckConstraint("status IN ('active', 'merged')", name=op.f("ck_topics_status")),
        sa.ForeignKeyConstraint(
            ["merged_into_id"], ["topics.id"], name=op.f("fk_topics_merged_into_id_topics")
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"], ["topics.id"], name=op.f("fk_topics_parent_id_topics")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_topics")),
        sa.UniqueConstraint("slug", name=op.f("uq_topics_slug")),
    )
    op.create_index(op.f("ix_topics_parent_id"), "topics", ["parent_id"], unique=False)
    op.create_table(
        "topic_aliases",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("scope_id", sa.BigInteger(), nullable=False),
        sa.Column("key", sa.Text(), nullable=False),
        sa.Column("label", sa.Text(), nullable=False),
        sa.Column("topic_id", sa.BigInteger(), nullable=False),
        sa.Column("origin", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["topic_id"],
            ["topics.id"],
            name=op.f("fk_topic_aliases_topic_id_topics"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_topic_aliases")),
        sa.UniqueConstraint("scope_id", "key", name=op.f("uq_topic_aliases_scope_id_key")),
    )
    op.create_index(op.f("ix_topic_aliases_topic_id"), "topic_aliases", ["topic_id"], unique=False)
    op.create_table(
        "competitor_profiles",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("competitor_id", sa.BigInteger(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.BigInteger(), nullable=True),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("prompt_version", sa.String(length=64), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("profile", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["competitor_id"],
            ["competitors.id"],
            name=op.f("fk_competitor_profiles_competitor_id_competitors"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_competitor_profiles_run_id_runs")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_competitor_profiles")),
        sa.UniqueConstraint(
            "competitor_id", "version", name=op.f("uq_competitor_profiles_competitor_id_version")
        ),
    )
    op.create_table(
        "landscape_reports",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("run_id", sa.BigInteger(), nullable=True),
        sa.Column("window_days", sa.Integer(), nullable=False),
        sa.Column(
            "competitor_slugs",
            postgresql.ARRAY(sa.Text()),
            server_default=sa.text("'{}'::text[]"),
            nullable=False,
        ),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("prompt_version", sa.String(length=64), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("narrative", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_landscape_reports_run_id_runs")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_landscape_reports")),
    )
    op.create_index(
        op.f("ix_landscape_reports_created_at"), "landscape_reports", ["created_at"], unique=False
    )
    op.create_table(
        "llm_calls",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("run_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("purpose", sa.String(length=32), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("prompt_version", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("items", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("request_chars", sa.Integer(), nullable=False),
        sa.Column("input_tokens", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("output_tokens", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("reasoning_tokens", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("cached_input_tokens", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("total_tokens", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("response_id", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "purpose IN ('content_analysis', 'change_summary', 'competitor_profile', 'landscape', 'topic_consolidation')",
            name=op.f("ck_llm_calls_purpose"),
        ),
        sa.CheckConstraint("status IN ('succeeded', 'failed')", name=op.f("ck_llm_calls_status")),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_llm_calls_run_id_runs"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_llm_calls")),
    )
    op.create_index(op.f("ix_llm_calls_created_at"), "llm_calls", ["created_at"], unique=False)
    op.create_index(op.f("ix_llm_calls_run_id"), "llm_calls", ["run_id"], unique=False)
    op.create_table(
        "content_analyses",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("competitor_id", sa.BigInteger(), nullable=False),
        sa.Column("content_item_id", sa.BigInteger(), nullable=False),
        sa.Column("content_version_id", sa.BigInteger(), nullable=False),
        sa.Column("run_id", sa.BigInteger(), nullable=True),
        sa.Column("method", sa.String(length=16), nullable=False),
        sa.Column("source_analysis_id", sa.BigInteger(), nullable=True),
        sa.Column("analyzer_version", sa.String(length=64), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("content_quality", sa.String(length=16), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("content_format", sa.String(length=32), nullable=False),
        sa.Column("intent", sa.String(length=16), nullable=True),
        sa.Column("funnel_stage", sa.String(length=16), nullable=True),
        sa.Column("primary_angle", sa.Text(), nullable=True),
        sa.Column("target_audiences", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("key_themes", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("keywords", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("positioning_claims", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("entities", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("language", sa.String(length=35), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("input_chars", sa.Integer(), nullable=False),
        sa.Column("input_truncated", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.CheckConstraint(
            "content_format IN ('article', 'tutorial', 'guide', 'listicle', 'comparison', 'case_study', 'announcement', 'news', 'opinion', 'interview', 'research', 'product_page', 'landing_page', 'pricing_page', 'documentation', 'changelog', 'event', 'other')",
            name=op.f("ck_content_analyses_content_format"),
        ),
        sa.CheckConstraint(
            "content_quality IN ('substantive', 'thin', 'boilerplate')",
            name=op.f("ck_content_analyses_content_quality"),
        ),
        sa.CheckConstraint(
            "funnel_stage IN ('awareness', 'consideration', 'decision', 'retention')",
            name=op.f("ck_content_analyses_funnel_stage"),
        ),
        sa.CheckConstraint(
            "intent IN ('informational', 'commercial', 'transactional', 'navigational', 'comparison')",
            name=op.f("ck_content_analyses_intent"),
        ),
        sa.CheckConstraint(
            "method IN ('llm', 'carried_forward')", name=op.f("ck_content_analyses_method")
        ),
        sa.ForeignKeyConstraint(
            ["competitor_id"],
            ["competitors.id"],
            name=op.f("fk_content_analyses_competitor_id_competitors"),
        ),
        sa.ForeignKeyConstraint(
            ["content_item_id"],
            ["content_items.id"],
            name=op.f("fk_content_analyses_content_item_id_content_items"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["content_version_id"],
            ["content_versions.id"],
            name=op.f("fk_content_analyses_content_version_id_content_versions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_content_analyses_run_id_runs")
        ),
        sa.ForeignKeyConstraint(
            ["source_analysis_id"],
            ["content_analyses.id"],
            name=op.f("fk_content_analyses_source_analysis_id_content_analyses"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_content_analyses")),
        sa.UniqueConstraint(
            "content_version_id",
            "analyzer_version",
            name=op.f("uq_content_analyses_content_version_id_analyzer_version"),
        ),
    )
    op.create_index(
        "ix_content_analyses_competitor_id_created_at",
        "content_analyses",
        ["competitor_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_content_analyses_content_item_id_created_at",
        "content_analyses",
        ["content_item_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "change_summaries",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("competitor_id", sa.BigInteger(), nullable=False),
        sa.Column("change_event_id", sa.BigInteger(), nullable=False),
        sa.Column("content_item_id", sa.BigInteger(), nullable=False),
        sa.Column("to_version_id", sa.BigInteger(), nullable=False),
        sa.Column("run_id", sa.BigInteger(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("significance", sa.String(length=16), nullable=False),
        sa.Column("categories", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("key_changes", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("prompt_version", sa.String(length=64), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "significance IN ('low', 'medium', 'high')",
            name=op.f("ck_change_summaries_significance"),
        ),
        sa.ForeignKeyConstraint(
            ["change_event_id"],
            ["change_events.id"],
            name=op.f("fk_change_summaries_change_event_id_change_events"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["competitor_id"],
            ["competitors.id"],
            name=op.f("fk_change_summaries_competitor_id_competitors"),
        ),
        sa.ForeignKeyConstraint(
            ["content_item_id"],
            ["content_items.id"],
            name=op.f("fk_change_summaries_content_item_id_content_items"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_change_summaries_run_id_runs")
        ),
        sa.ForeignKeyConstraint(
            ["to_version_id"],
            ["content_versions.id"],
            name=op.f("fk_change_summaries_to_version_id_content_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_change_summaries")),
        sa.UniqueConstraint("change_event_id", name=op.f("uq_change_summaries_change_event_id")),
        sa.UniqueConstraint("to_version_id", name=op.f("uq_change_summaries_to_version_id")),
    )
    op.create_index(
        op.f("ix_change_summaries_competitor_id"),
        "change_summaries",
        ["competitor_id"],
        unique=False,
    )
    op.create_table(
        "content_analysis_topics",
        sa.Column("analysis_id", sa.BigInteger(), nullable=False),
        sa.Column("topic_id", sa.BigInteger(), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("relevance", sa.Float(), nullable=False),
        sa.Column("label", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "role IN ('primary', 'secondary', 'subtopic')",
            name=op.f("ck_content_analysis_topics_role"),
        ),
        sa.ForeignKeyConstraint(
            ["analysis_id"],
            ["content_analyses.id"],
            name=op.f("fk_content_analysis_topics_analysis_id_content_analyses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["topic_id"], ["topics.id"], name=op.f("fk_content_analysis_topics_topic_id_topics")
        ),
        sa.PrimaryKeyConstraint("analysis_id", "topic_id", name=op.f("pk_content_analysis_topics")),
    )
    op.create_index(
        op.f("ix_content_analysis_topics_topic_id"),
        "content_analysis_topics",
        ["topic_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_content_analysis_topics_topic_id"), table_name="content_analysis_topics")
    op.drop_table("content_analysis_topics")
    op.drop_index(op.f("ix_change_summaries_competitor_id"), table_name="change_summaries")
    op.drop_table("change_summaries")
    op.drop_index("ix_content_analyses_content_item_id_created_at", table_name="content_analyses")
    op.drop_index("ix_content_analyses_competitor_id_created_at", table_name="content_analyses")
    op.drop_table("content_analyses")
    op.drop_index(op.f("ix_llm_calls_run_id"), table_name="llm_calls")
    op.drop_index(op.f("ix_llm_calls_created_at"), table_name="llm_calls")
    op.drop_table("llm_calls")
    op.drop_index(op.f("ix_landscape_reports_created_at"), table_name="landscape_reports")
    op.drop_table("landscape_reports")
    op.drop_table("competitor_profiles")
    op.drop_index(op.f("ix_topic_aliases_topic_id"), table_name="topic_aliases")
    op.drop_table("topic_aliases")
    op.drop_index(op.f("ix_topics_parent_id"), table_name="topics")
    op.drop_table("topics")
    # ### end Alembic commands ###
