"""Phase 5 generation layer: article drafts, their checkpointed steps, versions, research
sources and claim → source citations; runs.article_id; article LLM-call purposes.

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-14 21:09:41.984732
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0004"
down_revision: str | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "articles",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("opportunity_id", sa.BigInteger(), nullable=False),
        sa.Column("assessment_id", sa.BigInteger(), nullable=False),
        sa.Column("company_profile_id", sa.BigInteger(), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("current_step", sa.String(length=16), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("content_type", sa.String(length=32), nullable=False),
        sa.Column("target_audience", sa.Text(), nullable=True),
        sa.Column("search_intent", sa.String(length=32), nullable=True),
        sa.Column("angle", sa.Text(), nullable=True),
        sa.Column("brief", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("research_step_id", sa.BigInteger(), nullable=True),
        sa.Column("outline_version_id", sa.BigInteger(), nullable=True),
        sa.Column("draft_version_id", sa.BigInteger(), nullable=True),
        sa.Column("final_version_id", sa.BigInteger(), nullable=True),
        sa.Column("word_count", sa.Integer(), nullable=True),
        sa.Column("tokens_used", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("failed_step", sa.String(length=16), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "current_step IN ('brief', 'research', 'outline', 'draft', 'edit')",
            name=op.f("ck_articles_current_step"),
        ),
        sa.CheckConstraint(
            "failed_step IN ('brief', 'research', 'outline', 'draft', 'edit')",
            name=op.f("ck_articles_failed_step"),
        ),
        sa.CheckConstraint(
            "status IN ('queued', 'researching', 'outlining', 'drafting', 'editing', 'completed', 'failed', 'cancelled')",
            name=op.f("ck_articles_status"),
        ),
        sa.ForeignKeyConstraint(
            ["assessment_id"],
            ["opportunity_assessments.id"],
            name=op.f("fk_articles_assessment_id_opportunity_assessments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["company_profile_id"],
            ["company_profiles.id"],
            name=op.f("fk_articles_company_profile_id_company_profiles"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["opportunity_id"],
            ["opportunities.id"],
            name=op.f("fk_articles_opportunity_id_opportunities"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_articles")),
        sa.UniqueConstraint("slug", name=op.f("uq_articles_slug")),
    )
    op.create_index(
        op.f("ix_articles_opportunity_id"), "articles", ["opportunity_id"], unique=False
    )
    op.create_index(
        "ix_articles_status_created_at", "articles", ["status", "created_at"], unique=False
    )
    op.create_index(
        "uq_articles_live_opportunity",
        "articles",
        ["opportunity_id"],
        unique=True,
        postgresql_where=sa.text("NOT (status IN ('failed', 'cancelled'))"),
    )
    op.create_table(
        "article_steps",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("article_id", sa.BigInteger(), nullable=False),
        sa.Column("run_id", sa.BigInteger(), nullable=True),
        sa.Column("step", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("prompt_version", sa.String(length=64), nullable=True),
        sa.Column("model", sa.String(length=100), nullable=True),
        sa.Column("output", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("output_hash", sa.String(length=64), nullable=True),
        sa.Column("llm_calls", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("tokens", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('running', 'succeeded', 'failed')", name=op.f("ck_article_steps_status")
        ),
        sa.CheckConstraint(
            "step IN ('brief', 'research', 'outline', 'draft', 'edit')",
            name=op.f("ck_article_steps_step"),
        ),
        sa.ForeignKeyConstraint(
            ["article_id"],
            ["articles.id"],
            name=op.f("fk_article_steps_article_id_articles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_article_steps_run_id_runs"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_article_steps")),
    )
    op.create_index(
        "ix_article_steps_article_id_step_fingerprint",
        "article_steps",
        ["article_id", "step", "fingerprint"],
        unique=False,
    )
    op.create_index(op.f("ix_article_steps_run_id"), "article_steps", ["run_id"], unique=False)
    op.create_table(
        "article_sources",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("article_id", sa.BigInteger(), nullable=False),
        sa.Column("step_id", sa.BigInteger(), nullable=False),
        sa.Column("label", sa.String(length=8), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("requested_url", sa.Text(), nullable=True),
        sa.Column("domain", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("publisher", sa.Text(), nullable=True),
        sa.Column("published", sa.String(length=40), nullable=True),
        sa.Column("source_type", sa.String(length=24), nullable=False),
        sa.Column("relevance", sa.Float(), nullable=False),
        sa.Column("attribution_required", sa.Boolean(), nullable=False),
        sa.Column("excerpt", sa.Text(), nullable=True),
        sa.Column(
            "facts",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "retrieval",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "source_type IN ('official_docs', 'primary', 'research', 'organization', 'industry', 'news', 'company', 'competitor', 'other')",
            name=op.f("ck_article_sources_source_type"),
        ),
        sa.ForeignKeyConstraint(
            ["article_id"],
            ["articles.id"],
            name=op.f("fk_article_sources_article_id_articles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["step_id"],
            ["article_steps.id"],
            name=op.f("fk_article_sources_step_id_article_steps"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_article_sources")),
        sa.UniqueConstraint("step_id", "label", name=op.f("uq_article_sources_step_id_label")),
        sa.UniqueConstraint("step_id", "url", name=op.f("uq_article_sources_step_id_url")),
    )
    op.create_index(
        op.f("ix_article_sources_article_id"), "article_sources", ["article_id"], unique=False
    )
    op.create_table(
        "article_versions",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("article_id", sa.BigInteger(), nullable=False),
        sa.Column("step_id", sa.BigInteger(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("word_count", sa.Integer(), nullable=True),
        sa.Column(
            "issues",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "changes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("prompt_version", sa.String(length=64), nullable=True),
        sa.Column("model", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('outline', 'draft', 'final')", name=op.f("ck_article_versions_kind")
        ),
        sa.ForeignKeyConstraint(
            ["article_id"],
            ["articles.id"],
            name=op.f("fk_article_versions_article_id_articles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["step_id"],
            ["article_steps.id"],
            name=op.f("fk_article_versions_step_id_article_steps"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_article_versions")),
        sa.UniqueConstraint(
            "article_id", "kind", "number", name=op.f("uq_article_versions_article_id_kind_number")
        ),
    )
    op.create_index(
        op.f("ix_article_versions_step_id"), "article_versions", ["step_id"], unique=False
    )
    op.create_table(
        "article_citations",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("version_id", sa.BigInteger(), nullable=False),
        sa.Column("source_id", sa.BigInteger(), nullable=False),
        sa.Column("section_index", sa.Integer(), nullable=False),
        sa.Column("block_index", sa.Integer(), nullable=False),
        sa.Column("item_index", sa.Integer(), nullable=True),
        sa.Column("claim", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["article_sources.id"],
            name=op.f("fk_article_citations_source_id_article_sources"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["article_versions.id"],
            name=op.f("fk_article_citations_version_id_article_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_article_citations")),
    )
    op.create_index(
        op.f("ix_article_citations_source_id"), "article_citations", ["source_id"], unique=False
    )
    op.create_index(
        op.f("ix_article_citations_version_id"), "article_citations", ["version_id"], unique=False
    )
    op.add_column("runs", sa.Column("article_id", sa.BigInteger(), nullable=True))
    op.create_index(op.f("ix_runs_article_id"), "runs", ["article_id"], unique=False)
    op.create_foreign_key(
        op.f("fk_runs_article_id_articles"),
        "runs",
        "articles",
        ["article_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_articles_draft_version_id_article_versions"),
        "articles",
        "article_versions",
        ["draft_version_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_articles_final_version_id_article_versions"),
        "articles",
        "article_versions",
        ["final_version_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_articles_outline_version_id_article_versions"),
        "articles",
        "article_versions",
        ["outline_version_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_articles_research_step_id_article_steps"),
        "articles",
        "article_steps",
        ["research_step_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_constraint(op.f("ck_llm_calls_purpose"), "llm_calls", type_="check")
    op.create_check_constraint(
        op.f("ck_llm_calls_purpose"),
        "llm_calls",
        "purpose IN ('content_analysis', 'change_summary', 'competitor_profile', 'landscape', 'topic_consolidation', 'opportunity_interpretation', 'article_research', 'article_outline', 'article_draft', 'article_edit')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute(
        "DELETE FROM llm_calls WHERE purpose IN "
        "('article_research', 'article_outline', 'article_draft', 'article_edit')"
    )
    op.drop_constraint(op.f("ck_llm_calls_purpose"), "llm_calls", type_="check")
    op.create_check_constraint(
        op.f("ck_llm_calls_purpose"),
        "llm_calls",
        "purpose IN ('content_analysis', 'change_summary', 'competitor_profile', 'landscape', 'topic_consolidation', 'opportunity_interpretation')",
    )
    op.drop_constraint(
        op.f("fk_articles_draft_version_id_article_versions"), "articles", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_articles_final_version_id_article_versions"), "articles", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_articles_outline_version_id_article_versions"), "articles", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_articles_research_step_id_article_steps"), "articles", type_="foreignkey"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_runs_article_id_articles"), "runs", type_="foreignkey")
    op.drop_index(op.f("ix_runs_article_id"), table_name="runs")
    op.drop_column("runs", "article_id")
    op.drop_index(op.f("ix_article_citations_version_id"), table_name="article_citations")
    op.drop_index(op.f("ix_article_citations_source_id"), table_name="article_citations")
    op.drop_table("article_citations")
    op.drop_index(op.f("ix_article_versions_step_id"), table_name="article_versions")
    op.drop_table("article_versions")
    op.drop_index(op.f("ix_article_sources_article_id"), table_name="article_sources")
    op.drop_table("article_sources")
    op.drop_index(op.f("ix_article_steps_run_id"), table_name="article_steps")
    op.drop_index("ix_article_steps_article_id_step_fingerprint", table_name="article_steps")
    op.drop_table("article_steps")
    op.drop_index(
        "uq_articles_live_opportunity",
        table_name="articles",
        postgresql_where=sa.text("NOT (status IN ('failed', 'cancelled'))"),
    )
    op.drop_index("ix_articles_status_created_at", table_name="articles")
    op.drop_index(op.f("ix_articles_opportunity_id"), table_name="articles")
    op.drop_table("articles")
    # ### end Alembic commands ###
