"""Phase 2 history schema: competitors, runs, raw documents, content items/versions, changes.

Revision ID: 0001
Revises:
Create Date: 2026-09-13 15:56:26.788999
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "competitors",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("website", sa.Text(), nullable=False),
        sa.Column(
            "config",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_competitors")),
        sa.UniqueConstraint("slug", name=op.f("uq_competitors_slug")),
    )
    op.create_table(
        "raw_documents",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("competitor_id", sa.BigInteger(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("final_url", sa.Text(), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("http_status", sa.Integer(), nullable=False),
        sa.Column("content_type", sa.Text(), nullable=True),
        sa.Column("etag", sa.Text(), nullable=True),
        sa.Column("last_modified", sa.Text(), nullable=True),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("compression", sa.String(length=16), nullable=False),
        sa.Column("body", sa.LargeBinary(), nullable=False),
        sa.ForeignKeyConstraint(
            ["competitor_id"],
            ["competitors.id"],
            name=op.f("fk_raw_documents_competitor_id_competitors"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_raw_documents")),
    )
    op.create_index(
        "ix_raw_documents_competitor_id_url",
        "raw_documents",
        ["competitor_id", "url"],
        unique=False,
    )
    op.create_table(
        "runs",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("trigger", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("competitor_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "params",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "stats",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "summary",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('queued', 'running', 'succeeded', 'partial', 'failed')",
            name=op.f("ck_runs_status"),
        ),
        sa.CheckConstraint("trigger IN ('cli', 'api', 'schedule')", name=op.f("ck_runs_trigger")),
        sa.ForeignKeyConstraint(
            ["competitor_id"], ["competitors.id"], name=op.f("fk_runs_competitor_id_competitors")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_runs")),
    )
    op.create_index(
        "ix_runs_competitor_id_created_at", "runs", ["competitor_id", "created_at"], unique=False
    )
    op.create_table(
        "content_items",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("competitor_id", sa.BigInteger(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("content_type", sa.String(length=32), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column(
            "discovered_via",
            postgresql.ARRAY(sa.Text()),
            server_default=sa.text("'{}'::text[]"),
            nullable=False,
        ),
        sa.Column("in_baseline", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("duplicate_of_id", sa.BigInteger(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("published_at_source", sa.String(length=32), nullable=True),
        sa.Column("modified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sitemap_lastmod", sa.DateTime(timezone=True), nullable=True),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_fetched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_changed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("first_seen_run_id", sa.BigInteger(), nullable=True),
        sa.Column("etag", sa.Text(), nullable=True),
        sa.Column("last_modified_header", sa.Text(), nullable=True),
        sa.Column("current_version_id", sa.BigInteger(), nullable=True),
        sa.Column("version_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "published_at_source IN ('structured_data', 'meta', 'feed', 'sitemap_news', 'page')",
            name=op.f("ck_content_items_published_at_source"),
        ),
        sa.CheckConstraint(
            "status IN ('discovered', 'active', 'removed', 'duplicate')",
            name=op.f("ck_content_items_status"),
        ),
        sa.ForeignKeyConstraint(
            ["competitor_id"],
            ["competitors.id"],
            name=op.f("fk_content_items_competitor_id_competitors"),
        ),
        sa.ForeignKeyConstraint(
            ["duplicate_of_id"],
            ["content_items.id"],
            name=op.f("fk_content_items_duplicate_of_id_content_items"),
        ),
        sa.ForeignKeyConstraint(
            ["first_seen_run_id"], ["runs.id"], name=op.f("fk_content_items_first_seen_run_id_runs")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_content_items")),
        sa.UniqueConstraint(
            "competitor_id", "url", name=op.f("uq_content_items_competitor_id_url")
        ),
    )
    op.create_index(
        "ix_content_items_competitor_id_first_seen_at",
        "content_items",
        ["competitor_id", "first_seen_at"],
        unique=False,
    )
    op.create_index(
        "ix_content_items_competitor_id_published_at",
        "content_items",
        ["competitor_id", "published_at"],
        unique=False,
    )
    op.create_table(
        "run_events",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("run_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("level", sa.String(length=16), nullable=False),
        sa.Column("event", sa.String(length=64), nullable=False),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column(
            "data",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_run_events_run_id_runs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_run_events")),
    )
    op.create_index(op.f("ix_run_events_run_id"), "run_events", ["run_id"], unique=False)
    op.create_table(
        "content_versions",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("content_item_id", sa.BigInteger(), nullable=False),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.BigInteger(), nullable=True),
        sa.Column("raw_document_id", sa.BigInteger(), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("final_url", sa.Text(), nullable=False),
        sa.Column("canonical_url", sa.Text(), nullable=True),
        sa.Column("http_status", sa.Integer(), nullable=False),
        sa.Column("content_type", sa.String(length=32), nullable=False),
        sa.Column("classification_reason", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("author", sa.Text(), nullable=True),
        sa.Column("language", sa.String(length=35), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("published_at_source", sa.String(length=32), nullable=True),
        sa.Column("modified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("categories", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("tags", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("headings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("structured_types", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("word_count", sa.Integer(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("is_thin", sa.Boolean(), nullable=False),
        sa.Column("extractor_version", sa.String(length=64), nullable=False),
        sa.CheckConstraint(
            "published_at_source IN ('structured_data', 'meta', 'feed', 'sitemap_news', 'page')",
            name=op.f("ck_content_versions_published_at_source"),
        ),
        sa.ForeignKeyConstraint(
            ["content_item_id"],
            ["content_items.id"],
            name=op.f("fk_content_versions_content_item_id_content_items"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["raw_document_id"],
            ["raw_documents.id"],
            name=op.f("fk_content_versions_raw_document_id_raw_documents"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_content_versions_run_id_runs")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_content_versions")),
        sa.UniqueConstraint(
            "content_item_id",
            "version_no",
            name=op.f("uq_content_versions_content_item_id_version_no"),
        ),
    )
    op.create_index(
        op.f("ix_content_versions_content_item_id"),
        "content_versions",
        ["content_item_id"],
        unique=False,
    )
    # content_items.current_version_id <-> content_versions.content_item_id is circular,
    # so this foreign key can only be added once both tables exist.
    op.create_foreign_key(
        op.f("fk_content_items_current_version_id_content_versions"),
        "content_items",
        "content_versions",
        ["current_version_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_table(
        "change_events",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("competitor_id", sa.BigInteger(), nullable=False),
        sa.Column("content_item_id", sa.BigInteger(), nullable=False),
        sa.Column("run_id", sa.BigInteger(), nullable=True),
        sa.Column("change_type", sa.String(length=32), nullable=False),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_minor", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("from_version_id", sa.BigInteger(), nullable=True),
        sa.Column("to_version_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "details",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "change_type IN ('new', 'updated', 'pricing_changed', 'removed', 'restored')",
            name=op.f("ck_change_events_change_type"),
        ),
        sa.ForeignKeyConstraint(
            ["competitor_id"],
            ["competitors.id"],
            name=op.f("fk_change_events_competitor_id_competitors"),
        ),
        sa.ForeignKeyConstraint(
            ["content_item_id"],
            ["content_items.id"],
            name=op.f("fk_change_events_content_item_id_content_items"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["from_version_id"],
            ["content_versions.id"],
            name=op.f("fk_change_events_from_version_id_content_versions"),
        ),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], name=op.f("fk_change_events_run_id_runs")),
        sa.ForeignKeyConstraint(
            ["to_version_id"],
            ["content_versions.id"],
            name=op.f("fk_change_events_to_version_id_content_versions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_change_events")),
    )
    op.create_index(
        "ix_change_events_competitor_id_detected_at",
        "change_events",
        ["competitor_id", "detected_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_change_events_content_item_id"), "change_events", ["content_item_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_change_events_content_item_id"), table_name="change_events")
    op.drop_index("ix_change_events_competitor_id_detected_at", table_name="change_events")
    op.drop_table("change_events")
    op.drop_constraint(
        op.f("fk_content_items_current_version_id_content_versions"),
        "content_items",
        type_="foreignkey",
    )
    op.drop_index(op.f("ix_content_versions_content_item_id"), table_name="content_versions")
    op.drop_table("content_versions")
    op.drop_index(op.f("ix_run_events_run_id"), table_name="run_events")
    op.drop_table("run_events")
    op.drop_index("ix_content_items_competitor_id_published_at", table_name="content_items")
    op.drop_index("ix_content_items_competitor_id_first_seen_at", table_name="content_items")
    op.drop_table("content_items")
    op.drop_index("ix_runs_competitor_id_created_at", table_name="runs")
    op.drop_table("runs")
    op.drop_index("ix_raw_documents_competitor_id_url", table_name="raw_documents")
    op.drop_table("raw_documents")
    op.drop_table("competitors")
    # ### end Alembic commands ###
