"""Phase 6 validation layer: claim checks, originality flags and quality reports; revision
versions (parent, reason, issues addressed, tokens); the article's recommended version, quality
score and validation fields; Phase 6 statuses, steps and LLM-call purposes. Nothing here
publishes anything.

Revision ID: 0005
Revises: 0004
Create Date: 2026-09-14 22:17:18.690452
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0005"
down_revision: str | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_STATUSES = (
    "queued",
    "researching",
    "outlining",
    "drafting",
    "editing",
    "completed",
    "failed",
    "cancelled",
)
_PHASE6_STATUSES = ("validating", "revising", "ready", "needs_review")
_STEPS = ("brief", "research", "outline", "draft", "edit")
_PHASE6_STEPS = ("fact_check", "originality", "seo", "metrics", "judge", "decision", "revision")
_KINDS = ("outline", "draft", "final")
_PURPOSES = (
    "content_analysis",
    "change_summary",
    "competitor_profile",
    "landscape",
    "topic_consolidation",
    "opportunity_interpretation",
    "article_research",
    "article_outline",
    "article_draft",
    "article_edit",
)
_PHASE6_PURPOSES = (
    "fact_check",
    "claim_classification",
    "seo_package",
    "quality_judge",
    "article_revision",
)


def _sql(values: Sequence[str]) -> str:
    return "(" + ", ".join(f"'{v}'" for v in values) + ")"


def _replace_check(table: str, column: str, values: Sequence[str]) -> None:
    name = op.f(f"ck_{table}_{column}")
    op.drop_constraint(name, table, type_="check")
    op.create_check_constraint(name, table, f"{column} IN {_sql(values)}")


def _set_checks(
    *, statuses: Sequence[str], steps: Sequence[str], kinds: Sequence[str], purposes: Sequence[str]
) -> None:
    _replace_check("articles", "status", statuses)
    _replace_check("articles", "current_step", steps)
    _replace_check("articles", "failed_step", steps)
    _replace_check("article_steps", "step", steps)
    _replace_check("article_versions", "kind", kinds)
    _replace_check("llm_calls", "purpose", purposes)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "article_claim_checks",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("article_id", sa.BigInteger(), nullable=False),
        sa.Column("step_id", sa.BigInteger(), nullable=False),
        sa.Column("version_id", sa.BigInteger(), nullable=False),
        sa.Column("source_id", sa.BigInteger(), nullable=True),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("section_index", sa.Integer(), nullable=False),
        sa.Column("block_index", sa.Integer(), nullable=False),
        sa.Column("item_index", sa.Integer(), nullable=True),
        sa.Column("claim", sa.Text(), nullable=False),
        sa.Column("claim_hash", sa.String(length=64), nullable=False),
        sa.Column("verdict", sa.String(length=24), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column("evidence", sa.Text(), nullable=True),
        sa.Column(
            "evidence_verified", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("reread", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("claim_type", sa.String(length=32), nullable=True),
        sa.Column(
            "signals",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("reused_from_id", sa.BigInteger(), nullable=True),
        sa.Column("model", sa.String(length=100), nullable=True),
        sa.Column("prompt_version", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('cited', 'uncited')", name=op.f("ck_article_claim_checks_kind")
        ),
        sa.CheckConstraint(
            "verdict IN ('supported', 'partial', 'unsupported', 'contradicted', 'needs_verification', 'not_required')",
            name=op.f("ck_article_claim_checks_verdict"),
        ),
        sa.ForeignKeyConstraint(
            ["article_id"],
            ["articles.id"],
            name=op.f("fk_article_claim_checks_article_id_articles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["reused_from_id"],
            ["article_claim_checks.id"],
            name=op.f("fk_article_claim_checks_reused_from_id_article_claim_checks"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["article_sources.id"],
            name=op.f("fk_article_claim_checks_source_id_article_sources"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["step_id"],
            ["article_steps.id"],
            name=op.f("fk_article_claim_checks_step_id_article_steps"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["article_versions.id"],
            name=op.f("fk_article_claim_checks_version_id_article_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_article_claim_checks")),
    )
    op.create_index(
        "ix_article_claim_checks_article_id_claim_hash",
        "article_claim_checks",
        ["article_id", "claim_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_article_claim_checks_source_id"),
        "article_claim_checks",
        ["source_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_article_claim_checks_step_id"), "article_claim_checks", ["step_id"], unique=False
    )
    op.create_index(
        op.f("ix_article_claim_checks_version_id"),
        "article_claim_checks",
        ["version_id"],
        unique=False,
    )
    op.create_table(
        "article_originality_flags",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("article_id", sa.BigInteger(), nullable=False),
        sa.Column("step_id", sa.BigInteger(), nullable=False),
        sa.Column("version_id", sa.BigInteger(), nullable=False),
        sa.Column("section_index", sa.Integer(), nullable=False),
        sa.Column("block_index", sa.Integer(), nullable=False),
        sa.Column("item_index", sa.Integer(), nullable=True),
        sa.Column("passage", sa.Text(), nullable=False),
        sa.Column("source_kind", sa.String(length=16), nullable=False),
        sa.Column("source_label", sa.Text(), nullable=False),
        sa.Column("content_item_id", sa.BigInteger(), nullable=True),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("overlap_text", sa.Text(), nullable=False),
        sa.Column("similarity", sa.Float(), nullable=False),
        sa.Column("overlap_words", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "source_kind IN ('competitor', 'company')",
            name=op.f("ck_article_originality_flags_source_kind"),
        ),
        sa.ForeignKeyConstraint(
            ["article_id"],
            ["articles.id"],
            name=op.f("fk_article_originality_flags_article_id_articles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["content_item_id"],
            ["content_items.id"],
            name=op.f("fk_article_originality_flags_content_item_id_content_items"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["step_id"],
            ["article_steps.id"],
            name=op.f("fk_article_originality_flags_step_id_article_steps"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["article_versions.id"],
            name=op.f("fk_article_originality_flags_version_id_article_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_article_originality_flags")),
    )
    op.create_index(
        op.f("ix_article_originality_flags_content_item_id"),
        "article_originality_flags",
        ["content_item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_article_originality_flags_step_id"),
        "article_originality_flags",
        ["step_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_article_originality_flags_version_id"),
        "article_originality_flags",
        ["version_id"],
        unique=False,
    )
    op.create_table(
        "article_quality_reports",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("article_id", sa.BigInteger(), nullable=False),
        sa.Column("version_id", sa.BigInteger(), nullable=False),
        sa.Column("run_id", sa.BigInteger(), nullable=True),
        sa.Column("decision_step_id", sa.BigInteger(), nullable=False),
        sa.Column("fact_check_step_id", sa.BigInteger(), nullable=True),
        sa.Column("originality_step_id", sa.BigInteger(), nullable=True),
        sa.Column("seo_step_id", sa.BigInteger(), nullable=True),
        sa.Column("metrics_step_id", sa.BigInteger(), nullable=True),
        sa.Column("judge_step_id", sa.BigInteger(), nullable=True),
        sa.Column("overall_score", sa.Float(), nullable=False),
        sa.Column("breakdown", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("gates", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.Column(
            "issues",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("config_fingerprint", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["article_id"],
            ["articles.id"],
            name=op.f("fk_article_quality_reports_article_id_articles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["decision_step_id"],
            ["article_steps.id"],
            name=op.f("fk_article_quality_reports_decision_step_id_article_steps"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["fact_check_step_id"],
            ["article_steps.id"],
            name=op.f("fk_article_quality_reports_fact_check_step_id_article_steps"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["judge_step_id"],
            ["article_steps.id"],
            name=op.f("fk_article_quality_reports_judge_step_id_article_steps"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["metrics_step_id"],
            ["article_steps.id"],
            name=op.f("fk_article_quality_reports_metrics_step_id_article_steps"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["originality_step_id"],
            ["article_steps.id"],
            name=op.f("fk_article_quality_reports_originality_step_id_article_steps"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
            name=op.f("fk_article_quality_reports_run_id_runs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["seo_step_id"],
            ["article_steps.id"],
            name=op.f("fk_article_quality_reports_seo_step_id_article_steps"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["article_versions.id"],
            name=op.f("fk_article_quality_reports_version_id_article_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_article_quality_reports")),
    )
    op.create_index(
        "ix_article_quality_reports_article_id_created_at",
        "article_quality_reports",
        ["article_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_article_quality_reports_decision_step_id"),
        "article_quality_reports",
        ["decision_step_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_article_quality_reports_version_id"),
        "article_quality_reports",
        ["version_id"],
        unique=False,
    )
    op.add_column("article_steps", sa.Column("version_id", sa.BigInteger(), nullable=True))
    op.create_index(
        op.f("ix_article_steps_version_id"), "article_steps", ["version_id"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_article_steps_version_id_article_versions"),
        "article_steps",
        "article_versions",
        ["version_id"],
        ["id"],
        ondelete="SET NULL",
        use_alter=True,
    )
    op.add_column(
        "article_versions", sa.Column("parent_version_id", sa.BigInteger(), nullable=True)
    )
    op.add_column("article_versions", sa.Column("reason", sa.Text(), nullable=True))
    op.add_column(
        "article_versions",
        sa.Column(
            "issues_addressed",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
    )
    op.add_column(
        "article_versions",
        sa.Column("tokens", sa.Integer(), server_default=sa.text("0"), nullable=False),
    )
    op.create_foreign_key(
        op.f("fk_article_versions_parent_version_id_article_versions"),
        "article_versions",
        "article_versions",
        ["parent_version_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column("articles", sa.Column("recommended_version_id", sa.BigInteger(), nullable=True))
    op.add_column("articles", sa.Column("quality_report_id", sa.BigInteger(), nullable=True))
    op.add_column("articles", sa.Column("quality_score", sa.Float(), nullable=True))
    op.add_column(
        "articles",
        sa.Column("revision_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
    )
    op.add_column(
        "articles",
        sa.Column("quality_tokens_used", sa.Integer(), server_default=sa.text("0"), nullable=False),
    )
    op.add_column("articles", sa.Column("validated_at", sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(
        op.f("fk_articles_recommended_version_id_article_versions"),
        "articles",
        "article_versions",
        ["recommended_version_id"],
        ["id"],
        ondelete="SET NULL",
        use_alter=True,
    )
    op.create_foreign_key(
        op.f("fk_articles_quality_report_id_article_quality_reports"),
        "articles",
        "article_quality_reports",
        ["quality_report_id"],
        ["id"],
        ondelete="SET NULL",
        use_alter=True,
    )
    # ### end Alembic commands ###
    _set_checks(
        statuses=_STATUSES + _PHASE6_STATUSES,
        steps=_STEPS + _PHASE6_STEPS,
        kinds=(*_KINDS, "revision"),
        purposes=_PURPOSES + _PHASE6_PURPOSES,
    )


def downgrade() -> None:
    # Rows the Phase 5 schema can't hold: validated articles go back to completed, Phase 6
    # steps (and with them revision versions, claim checks, flags and reports) are removed.
    op.execute(
        "UPDATE articles SET status = 'completed', current_step = NULL "
        "WHERE status IN ('validating', 'revising', 'ready', 'needs_review')"
    )
    op.execute(
        "UPDATE articles SET failed_step = NULL WHERE failed_step IN ('fact_check', 'originality', 'seo', 'metrics', 'judge', 'decision', 'revision')"
    )
    op.execute(
        "UPDATE articles SET current_step = NULL WHERE current_step IN ('fact_check', 'originality', 'seo', 'metrics', 'judge', 'decision', 'revision')"
    )
    op.execute("UPDATE articles SET recommended_version_id = NULL, quality_report_id = NULL")
    op.execute("DELETE FROM article_versions WHERE kind = 'revision'")
    op.execute(
        "DELETE FROM article_steps WHERE step IN ('fact_check', 'originality', 'seo', 'metrics', 'judge', 'decision', 'revision')"
    )
    op.execute(
        "DELETE FROM llm_calls WHERE purpose IN "
        "('fact_check', 'claim_classification', 'seo_package', 'quality_judge', 'article_revision')"
    )
    _set_checks(statuses=_STATUSES, steps=_STEPS, kinds=_KINDS, purposes=_PURPOSES)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_articles_quality_report_id_article_quality_reports"),
        "articles",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_articles_recommended_version_id_article_versions"), "articles", type_="foreignkey"
    )
    op.drop_column("articles", "validated_at")
    op.drop_column("articles", "quality_tokens_used")
    op.drop_column("articles", "revision_count")
    op.drop_column("articles", "quality_score")
    op.drop_column("articles", "quality_report_id")
    op.drop_column("articles", "recommended_version_id")
    op.drop_constraint(
        op.f("fk_article_versions_parent_version_id_article_versions"),
        "article_versions",
        type_="foreignkey",
    )
    op.drop_column("article_versions", "tokens")
    op.drop_column("article_versions", "issues_addressed")
    op.drop_column("article_versions", "reason")
    op.drop_column("article_versions", "parent_version_id")
    op.drop_constraint(
        op.f("fk_article_steps_version_id_article_versions"), "article_steps", type_="foreignkey"
    )
    op.drop_index(op.f("ix_article_steps_version_id"), table_name="article_steps")
    op.drop_column("article_steps", "version_id")
    op.drop_index(
        op.f("ix_article_quality_reports_version_id"), table_name="article_quality_reports"
    )
    op.drop_index(
        op.f("ix_article_quality_reports_decision_step_id"), table_name="article_quality_reports"
    )
    op.drop_index(
        "ix_article_quality_reports_article_id_created_at", table_name="article_quality_reports"
    )
    op.drop_table("article_quality_reports")
    op.drop_index(
        op.f("ix_article_originality_flags_version_id"), table_name="article_originality_flags"
    )
    op.drop_index(
        op.f("ix_article_originality_flags_step_id"), table_name="article_originality_flags"
    )
    op.drop_index(
        op.f("ix_article_originality_flags_content_item_id"), table_name="article_originality_flags"
    )
    op.drop_table("article_originality_flags")
    op.drop_index(op.f("ix_article_claim_checks_version_id"), table_name="article_claim_checks")
    op.drop_index(op.f("ix_article_claim_checks_step_id"), table_name="article_claim_checks")
    op.drop_index(op.f("ix_article_claim_checks_source_id"), table_name="article_claim_checks")
    op.drop_index(
        "ix_article_claim_checks_article_id_claim_hash", table_name="article_claim_checks"
    )
    op.drop_table("article_claim_checks")
    # ### end Alembic commands ###
