"""Phase 4 recommendation layer: versioned company profiles, content opportunities,
their assessments (score history), evidence, and events.

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-14 01:01:46.962314
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "company_profiles",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("scoring_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("profile", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_company_profiles")),
        sa.UniqueConstraint("version", name=op.f("uq_company_profiles_version")),
    )
    op.create_index(
        op.f("ix_company_profiles_fingerprint"), "company_profiles", ["fingerprint"], unique=False
    )
    op.create_table(
        "opportunities",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("key", sa.Text(), nullable=False),
        sa.Column("topic_id", sa.BigInteger(), nullable=True),
        sa.Column("topic_label", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("status_note", sa.Text(), nullable=True),
        sa.Column("status_changed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("current_assessment_id", sa.BigInteger(), nullable=True),
        sa.Column("last_scored_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('new', 'reviewed', 'approved', 'rejected', 'used', 'expired')",
            name=op.f("ck_opportunities_status"),
        ),
        sa.ForeignKeyConstraint(
            ["topic_id"], ["topics.id"], name=op.f("fk_opportunities_topic_id_topics")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_opportunities")),
        sa.UniqueConstraint("key", name=op.f("uq_opportunities_key")),
    )
    op.create_index(
        "ix_opportunities_status_score", "opportunities", ["status", "score"], unique=False
    )
    op.create_index(op.f("ix_opportunities_topic_id"), "opportunities", ["topic_id"], unique=False)
    op.create_table(
        "opportunity_assessments",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("opportunity_id", sa.BigInteger(), nullable=False),
        sa.Column("run_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("previous_assessment_id", sa.BigInteger(), nullable=True),
        sa.Column("company_profile_id", sa.BigInteger(), nullable=False),
        sa.Column("scoring_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("input_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("window_days", sa.Integer(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("breakdown", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("gaps", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("suggestion", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("signals", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("change", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("interpretation_status", sa.String(length=16), nullable=False),
        sa.Column("interpretation", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("interpretation_fingerprint", sa.String(length=64), nullable=True),
        sa.Column("interpretation_model", sa.String(length=100), nullable=True),
        sa.Column("interpretation_prompt_version", sa.String(length=64), nullable=True),
        sa.Column("interpretation_error", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "interpretation_status IN ('pending', 'ok', 'reused', 'failed', 'skipped')",
            name=op.f("ck_opportunity_assessments_interpretation_status"),
        ),
        sa.ForeignKeyConstraint(
            ["company_profile_id"],
            ["company_profiles.id"],
            name=op.f("fk_opportunity_assessments_company_profile_id_company_profiles"),
        ),
        sa.ForeignKeyConstraint(
            ["opportunity_id"],
            ["opportunities.id"],
            name=op.f("fk_opportunity_assessments_opportunity_id_opportunities"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["previous_assessment_id"],
            ["opportunity_assessments.id"],
            name=op.f("fk_opportunity_assessments_previous_assessment_id_opportunity_assessments"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
            name=op.f("fk_opportunity_assessments_run_id_runs"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_opportunity_assessments")),
    )
    op.create_index(
        "ix_opportunity_assessments_opportunity_id_created_at",
        "opportunity_assessments",
        ["opportunity_id", "created_at"],
        unique=False,
    )
    # opportunities <-> opportunity_assessments reference each other: add this one last.
    op.create_foreign_key(
        op.f("fk_opportunities_current_assessment_id_opportunity_assessments"),
        "opportunities",
        "opportunity_assessments",
        ["current_assessment_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_table(
        "opportunity_events",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("opportunity_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("from_status", sa.String(length=16), nullable=True),
        sa.Column("to_status", sa.String(length=16), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("actor", sa.String(length=16), nullable=False),
        sa.Column("run_id", sa.BigInteger(), nullable=True),
        sa.Column("assessment_id", sa.BigInteger(), nullable=True),
        sa.CheckConstraint(
            "kind IN ('created', 'rescored', 'status_changed', 'expired', 'reopened')",
            name=op.f("ck_opportunity_events_kind"),
        ),
        sa.ForeignKeyConstraint(
            ["assessment_id"],
            ["opportunity_assessments.id"],
            name=op.f("fk_opportunity_events_assessment_id_opportunity_assessments"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["opportunity_id"],
            ["opportunities.id"],
            name=op.f("fk_opportunity_events_opportunity_id_opportunities"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
            name=op.f("fk_opportunity_events_run_id_runs"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_opportunity_events")),
    )
    op.create_index(
        "ix_opportunity_events_opportunity_id_created_at",
        "opportunity_events",
        ["opportunity_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "opportunity_evidence",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("assessment_id", sa.BigInteger(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("ref_id", sa.BigInteger(), nullable=True),
        sa.Column("competitor_id", sa.BigInteger(), nullable=True),
        sa.Column("label", sa.Text(), nullable=False),
        sa.Column(
            "data",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('topic_metrics', 'topic_trend', 'content', 'competitor_profile', 'gap', 'company_profile', 'related_topic')",
            name=op.f("ck_opportunity_evidence_kind"),
        ),
        sa.ForeignKeyConstraint(
            ["assessment_id"],
            ["opportunity_assessments.id"],
            name=op.f("fk_opportunity_evidence_assessment_id_opportunity_assessments"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["competitor_id"],
            ["competitors.id"],
            name=op.f("fk_opportunity_evidence_competitor_id_competitors"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_opportunity_evidence")),
    )
    op.create_index(
        op.f("ix_opportunity_evidence_assessment_id"),
        "opportunity_evidence",
        ["assessment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_opportunity_evidence_competitor_id"),
        "opportunity_evidence",
        ["competitor_id"],
        unique=False,
    )
    op.create_index(
        "ix_opportunity_evidence_kind_ref_id",
        "opportunity_evidence",
        ["kind", "ref_id"],
        unique=False,
    )
    # ### end Alembic commands ###
    # llm_calls gains a purpose: swap its CHECK constraint (autogenerate doesn't track CHECKs).
    op.drop_constraint(op.f("ck_llm_calls_purpose"), "llm_calls", type_="check")
    op.create_check_constraint(
        op.f("ck_llm_calls_purpose"),
        "llm_calls",
        "purpose IN ('content_analysis', 'change_summary', 'competitor_profile', 'landscape', 'topic_consolidation', 'opportunity_interpretation')",
    )


def downgrade() -> None:
    op.execute("DELETE FROM llm_calls WHERE purpose = 'opportunity_interpretation'")
    op.drop_constraint(op.f("ck_llm_calls_purpose"), "llm_calls", type_="check")
    op.create_check_constraint(
        op.f("ck_llm_calls_purpose"),
        "llm_calls",
        "purpose IN ('content_analysis', 'change_summary', 'competitor_profile', 'landscape', 'topic_consolidation')",
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_opportunities_current_assessment_id_opportunity_assessments"),
        "opportunities",
        type_="foreignkey",
    )
    op.drop_index("ix_opportunity_evidence_kind_ref_id", table_name="opportunity_evidence")
    op.drop_index(op.f("ix_opportunity_evidence_competitor_id"), table_name="opportunity_evidence")
    op.drop_index(op.f("ix_opportunity_evidence_assessment_id"), table_name="opportunity_evidence")
    op.drop_table("opportunity_evidence")
    op.drop_index(
        "ix_opportunity_events_opportunity_id_created_at", table_name="opportunity_events"
    )
    op.drop_table("opportunity_events")
    op.drop_index(
        "ix_opportunity_assessments_opportunity_id_created_at", table_name="opportunity_assessments"
    )
    op.drop_table("opportunity_assessments")
    op.drop_index(op.f("ix_opportunities_topic_id"), table_name="opportunities")
    op.drop_index("ix_opportunities_status_score", table_name="opportunities")
    op.drop_table("opportunities")
    op.drop_index(op.f("ix_company_profiles_fingerprint"), table_name="company_profiles")
    op.drop_table("company_profiles")
    # ### end Alembic commands ###
